#!/bin/sh

echo "Formatting the .cs files..."

# Valida HoosPath
git config core.hooks

# Format the code
FILES=$(git diff --cached --name-only --diff-filter=ACM "*.cs")
if [ -n "$FILES" ]
then
    dotnet-format ConsoleApp.sln --include $FILES
    echo "$FILES" | xargs git add
fi

if [ $? -ne 0 ]; then
  echo "Error formatting changes...."
  exit 1
fi

echo "Formatting done!"

exit 0